// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzinvalidlnlhindttbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aW52YWxpZGxubGhpbmR0dGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjM5NTksImV4cCI6MjA2NjczOTk1OX0.Wj8TYNXOlMVGZjrOONL3gWx-IAq6T-6ajpzM82ehuJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);